jwt:
  secret_key: OIJha97dAJND9P734KJNp9u8d89wiun3479rfsdpioqwjed
  algorithm: HS256

  expiration:
    access_token: 30 # Minutes
    refresh_token: 1440 # Minutes
  
email_verification:

  username: fmerm2004@gmail.com
  password: fjjh jjyb lltr oonk

  from_data: 
    name: FM ERM Support
    mail: fmerm2004@gmail.com

  token_expiration: 60 # Minutes
  
  use_credentials: true

  server:
    port: 587
    host: smtp.gmail.com
    start_tls: true
    use_ssl: false
  
database:
  url: postgresql://postgres:ermsupermamalonjasjas123@db.hrxnndpvssbwviwzeedm.supabase.co:5432/postgres
  