jwt:
  secret_key: your-super-mega-secret-key-change-this-in-production
  algorithm: HS256

  expiration:
    access_token: 30 # Minutes
    refresh_token: 1440 # Minutes
  
email_verification:

  username: your-email@gmail.com
  password: your-app-password

  from_data: 
    name: ERM Support
    mail: your-email@gmail.com

  token_expiration: 60 # Minutes
  
  use_credentials: true

  server:
    port: 587
    host: smtp.gmail.com
    start_tls: true
    use_ssl: false
  
database:
  url: postgresql://user:password@localhost:5432/erm_db