"""subscription status enum

Revision ID: 0f5424453b35
Revises: 6b20052cac8e
Create Date: 2026-05-08 23:21:52.158925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f5424453b35'
down_revision: Union[str, Sequence[str], None] = '6b20052cac8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription', 'status',
               existing_type=postgresql.ENUM('pending', 'authorized', 'cancelled', 'expired', name='subscriptionStatusEnum'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('pending', 'authorized', 'cancelled', 'expired', name='subscriptionStatusEnum'),
               existing_nullable=False)
    # ### end Alembic commands ###
