"""provider_subs_id

Revision ID: 0faaac52e9b6
Revises: f7a792343cfd
Create Date: 2026-06-02 15:04:10.542092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0faaac52e9b6'
down_revision: Union[str, Sequence[str], None] = 'f7a792343cfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('provider_subscription_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'provider_subscription_id')
    # ### end Alembic commands ###
