"""enum subscriptions

Revision ID: 15090be472aa
Revises: 33d4c48f4667
Create Date: 2026-05-05 13:16:54.799892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Enum

subscription_status_enum = Enum(
    "pending",
    "authorized",
    "cancelled",
    "expired",
    name="subscriptionStatusEnum"
)


# revision identifiers, used by Alembic.
revision: str = '15090be472aa'
down_revision: Union[str, Sequence[str], None] = '33d4c48f4667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    subscription_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('subscription', sa.Column('status', sa.Enum('pending', 'active', 'cancelled', 'expired', name='subscriptionStatusEnum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'status')
    # ### end Alembic commands ###
