"""quit current from cronograma db

Revision ID: 1bc19a3b3a5c
Revises: e7cacb788f2a
Create Date: 2026-06-09 19:18:45.650775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bc19a3b3a5c'
down_revision: Union[str, Sequence[str], None] = 'e7cacb788f2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_schedules', 'is_current')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_schedules', sa.Column('is_current', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
