"""nullable=False in company_id

Revision ID: 1ecb9b7056b7
Revises: 6a516ec53988
Create Date: 2026-03-08 18:15:41.662898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ecb9b7056b7'
down_revision: Union[str, Sequence[str], None] = '6a516ec53988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('contacts', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('production', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('production', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('production', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('production', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('contacts', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('contacts', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
