"""create financery data again, lol

Revision ID: 2e956f79c000
Revises: 6c19d7fdfddd
Create Date: 2026-03-25 22:55:08.784142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2e956f79c000'
down_revision: Union[str, Sequence[str], None] = '6c19d7fdfddd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receivables_amount'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_company_id'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_description'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_due_date'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_id'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_payer_id'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_payer_name'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_receiver_id'), table_name='receivables')
    op.drop_table('receivables')
    op.drop_index(op.f('ix_sells_client_id'), table_name='sells')
    op.drop_index(op.f('ix_sells_client_name'), table_name='sells')
    op.drop_index(op.f('ix_sells_company_id'), table_name='sells')
    op.drop_index(op.f('ix_sells_expenses'), table_name='sells')
    op.drop_index(op.f('ix_sells_id'), table_name='sells')
    op.drop_index(op.f('ix_sells_income'), table_name='sells')
    op.drop_index(op.f('ix_sells_profit'), table_name='sells')
    op.drop_table('sells')
    op.drop_index(op.f('ix_debts_amount'), table_name='debts')
    op.drop_index(op.f('ix_debts_company_id'), table_name='debts')
    op.drop_index(op.f('ix_debts_creditor'), table_name='debts')
    op.drop_index(op.f('ix_debts_id'), table_name='debts')
    op.drop_table('debts')
    op.drop_index(op.f('ix_notifications_company_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_payments_amount'), table_name='payments')
    op.drop_index(op.f('ix_payments_company_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_due_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('debt_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('paid', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('paid_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('payments_company_id_fkey')),
    sa.ForeignKeyConstraint(['debt_id'], ['debts.id'], name=op.f('payments_debt_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payments_pkey'))
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_due_date'), 'payments', ['due_date'], unique=False)
    op.create_index(op.f('ix_payments_company_id'), 'payments', ['company_id'], unique=False)
    op.create_index(op.f('ix_payments_amount'), 'payments', ['amount'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('notifications_company_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_company_id'), 'notifications', ['company_id'], unique=False)
    op.create_table('debts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('creditor', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('number_of_installments', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('debts_company_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('debts_pkey'))
    )
    op.create_index(op.f('ix_debts_id'), 'debts', ['id'], unique=False)
    op.create_index(op.f('ix_debts_creditor'), 'debts', ['creditor'], unique=False)
    op.create_index(op.f('ix_debts_company_id'), 'debts', ['company_id'], unique=False)
    op.create_index(op.f('ix_debts_amount'), 'debts', ['amount'], unique=False)
    op.create_table('sells',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('client_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('income', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expenses', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('profit', sa.INTEGER(), sa.Computed('(income - expenses)', persisted=True), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('planning', 'cutting', 'pre_assembly', 'lamination', 'truck_loading', 'installation', 'completed', 'cancelled', name='statusenum'), autoincrement=False, nullable=False),
    sa.Column('delivery', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('carpenter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['carpenter_id'], ['users.id'], name=op.f('sells_carpenter_id_fkey')),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], name=op.f('sells_client_id_fkey')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('sells_company_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('sells_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('sells_pkey'))
    )
    op.create_index(op.f('ix_sells_profit'), 'sells', ['profit'], unique=False)
    op.create_index(op.f('ix_sells_income'), 'sells', ['income'], unique=False)
    op.create_index(op.f('ix_sells_id'), 'sells', ['id'], unique=False)
    op.create_index(op.f('ix_sells_expenses'), 'sells', ['expenses'], unique=False)
    op.create_index(op.f('ix_sells_company_id'), 'sells', ['company_id'], unique=False)
    op.create_index(op.f('ix_sells_client_name'), 'sells', ['client_name'], unique=False)
    op.create_index(op.f('ix_sells_client_id'), 'sells', ['client_id'], unique=False)
    op.create_table('receivables',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.NUMERIC(), autoincrement=False, nullable=False),
    sa.Column('due_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('payer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payer_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('paid_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('receivables_company_id_fkey')),
    sa.ForeignKeyConstraint(['payer_id'], ['contacts.id'], name=op.f('receivables_payer_id_fkey')),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name=op.f('receivables_receiver_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('receivables_pkey'))
    )
    op.create_index(op.f('ix_receivables_receiver_id'), 'receivables', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_receivables_payer_name'), 'receivables', ['payer_name'], unique=False)
    op.create_index(op.f('ix_receivables_payer_id'), 'receivables', ['payer_id'], unique=False)
    op.create_index(op.f('ix_receivables_id'), 'receivables', ['id'], unique=False)
    op.create_index(op.f('ix_receivables_due_date'), 'receivables', ['due_date'], unique=False)
    op.create_index(op.f('ix_receivables_description'), 'receivables', ['description'], unique=False)
    op.create_index(op.f('ix_receivables_company_id'), 'receivables', ['company_id'], unique=False)
    op.create_index(op.f('ix_receivables_amount'), 'receivables', ['amount'], unique=False)
    # ### end Alembic commands ###
