"""payments db

Revision ID: 31bae4b28f1a
Revises: 4cf27a197615
Create Date: 2026-06-02 19:35:16.655932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31bae4b28f1a'
down_revision: Union[str, Sequence[str], None] = '4cf27a197615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription', 'current_period_start',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('subscription', 'current_period_end',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_index(op.f('ix_subscription_current_period_end'), 'subscription', ['current_period_end'], unique=False)
    op.create_index(op.f('ix_subscription_current_period_start'), 'subscription', ['current_period_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_current_period_start'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_current_period_end'), table_name='subscription')
    op.alter_column('subscription', 'current_period_end',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('subscription', 'current_period_start',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
