"""photos and pdfs path in db

Revision ID: 3e92a6dc7da3
Revises: d1aca8bc09e4
Create Date: 2026-04-23 21:52:18.750174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e92a6dc7da3'
down_revision: Union[str, Sequence[str], None] = 'd1aca8bc09e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
