"""fix names in pay models

Revision ID: 41c4be0cbe27
Revises: 15090be472aa
Create Date: 2026-05-06 16:33:22.799647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41c4be0cbe27'
down_revision: Union[str, Sequence[str], None] = '15090be472aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('mp_subscription_id', sa.String(), nullable=True))
    op.drop_column('subscription', 'mp_payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('mp_payment_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('subscription', 'mp_subscription_id')
    # ### end Alembic commands ###
