"""update enums

Revision ID: 43b9d405a26b
Revises: 1bc19a3b3a5c
Create Date: 2026-06-11 19:53:35.095570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b9d405a26b'
down_revision: Union[str, Sequence[str], None] = '1bc19a3b3a5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from alembic import op

def upgrade():

    # types
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM pg_type
            WHERE typname = 'types'
        ) THEN
            CREATE TYPE types AS ENUM (
                'arquiteto',
                'pessoal',
                'colaborador',
                'cliente'
            );
        END IF;
    END$$;
    """)

    # subscriptionstatusenum
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1
            FROM pg_type
            WHERE typname = 'subscriptionstatusenum'
        ) THEN
            CREATE TYPE subscriptionstatusenum AS ENUM (
                'PENDING',
                'PAID',
                'CANCELLED',
                'EXPIRED',
                'REFUNDED'
            );
        END IF;
    END$$;
    """)


def downgrade():

    op.execute("""
    DO $$
    BEGIN
        IF EXISTS (
            SELECT 1
            FROM pg_type
            WHERE typname = 'subscriptionstatusenum'
        ) THEN
            DROP TYPE subscriptionstatusenum;
        END IF;
    END$$;
    """)

    op.execute("""
    DO $$
    BEGIN
        IF EXISTS (
            SELECT 1
            FROM pg_type
            WHERE typname = 'types'
        ) THEN
            DROP TYPE types;
        END IF;
    END$$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TYPE subscriptionstatusenum
        RENAME TO subscriptionstatusenum_new;
    """)

    op.execute("""
        CREATE TYPE subscriptionstatusenum AS ENUM (
            'pending',
            'active',
            'cancelled',
            'expired'
        );
    """)

    op.execute("""
        ALTER TABLE subscription
        ALTER COLUMN status
        TYPE subscriptionstatusenum
        USING (
            CASE status::text
                WHEN 'PENDING' THEN 'pending'
                WHEN 'PAID' THEN 'active'
                WHEN 'CANCELLED' THEN 'cancelled'
                WHEN 'EXPIRED' THEN 'expired'
            END
        )::subscriptionstatusenum;
    """)

    op.execute("DROP TYPE subscriptionstatusenum_new;")


    op.execute("""
        ALTER TYPE types
        RENAME TO types_new;
    """)

    op.execute("""
        CREATE TYPE types AS ENUM (
            'architect',
            'personal',
            'employed',
            'client'
        );
    """)

    op.execute("""
        ALTER TABLE users
        ALTER COLUMN type
        TYPE types
        USING (
            CASE type::text
                WHEN 'arquiteto' THEN 'architect'
                WHEN 'pessoal' THEN 'personal'
                WHEN 'colaborador' THEN 'employed'
                WHEN 'cliente' THEN 'client'
            END
        )::types;
    """)

    op.execute("DROP TYPE types_new;")
    # ### end Alembic commands ###
