"""delete company id from comments

Revision ID: 462c4b990765
Revises: c199d908b16e
Create Date: 2026-05-22 21:07:14.854015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '462c4b990765'
down_revision: Union[str, Sequence[str], None] = 'c199d908b16e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_company_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_session_token'), table_name='comments')
    op.create_index(op.f('ix_comments_session_token'), 'comments', ['session_token'], unique=False)
    op.drop_constraint(op.f('comments_company_id_fkey'), 'comments', type_='foreignkey')
    op.drop_column('comments', 'company_id')
    op.alter_column('shared_projects', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shared_projects', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('comments', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('comments_company_id_fkey'), 'comments', 'companies', ['company_id'], ['id'])
    op.drop_index(op.f('ix_comments_session_token'), table_name='comments')
    op.create_index(op.f('ix_comments_session_token'), 'comments', ['session_token'], unique=True)
    op.create_index(op.f('ix_comments_company_id'), 'comments', ['company_id'], unique=False)
    # ### end Alembic commands ###
