"""installments in sells table

Revision ID: 4a0a03f7496c
Revises: 7dc04fbab67e
Create Date: 2026-03-30 22:02:31.570877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a0a03f7496c'
down_revision: Union[str, Sequence[str], None] = '7dc04fbab67e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sells', 'profit')
    op.alter_column('sells', 'income',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(),
               postgresql_using='income::numeric',
               existing_nullable=False)
    
    op.alter_column('sells', 'expenses',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(),
               postgresql_using='income::numeric',
               existing_nullable=False)
    
    op.add_column(
    'sells',
    sa.Column(
        'profit',
        sa.DECIMAL(),
        sa.Computed('(income - expenses)', persisted=True)
    )
)
    
    op.alter_column('debts', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('pending', 'cancelled', 'paid', 'overdue', name='debtstatusenum'),
               postgresql_using="status::debtstatusenum",
               nullable=False)
    op.add_column('sells', sa.Column('installments', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sells_installments'), 'sells', ['installments'], unique=False)
    op.drop_column('sells', 'type')
    op.alter_column('users', 'verification_code_expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'verification_code_expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.add_column('sells', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_sells_installments'), table_name='sells')
    op.alter_column('sells', 'profit',
               existing_type=sa.DECIMAL(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.Computed('(income - expenses)', persisted=True))
    op.alter_column('sells', 'expenses',
               existing_type=sa.DECIMAL(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('sells', 'income',
               existing_type=sa.DECIMAL(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('sells', 'installments')
    op.alter_column('debts', 'status',
               existing_type=sa.Enum('pending', 'cancelled', 'paid', 'overdue', name='debtstatusenum'),
               type_=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
