"""create notification

Revision ID: 4aea36098c91
Revises: 78f31edf206a
Create Date: 2026-03-16 23:38:30.183673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aea36098c91'
down_revision: Union[str, Sequence[str], None] = '78f31edf206a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_company_join_requests_message'), 'company_join_requests', ['message'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_join_requests_message'), table_name='company_join_requests')
    # ### end Alembic commands ###
