"""string in payments

Revision ID: 4cf27a197615
Revises: 0faaac52e9b6
Create Date: 2026-06-02 19:32:25.575512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cf27a197615'
down_revision: Union[str, Sequence[str], None] = '0faaac52e9b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription', 'status',
               existing_type=postgresql.ENUM('active', 'canceled', 'overdue', name='subscriptionstatusenum'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription', 'status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('active', 'canceled', 'overdue', name='subscriptionstatusenum'),
               existing_nullable=False)
    # ### end Alembic commands ###
