"""plans db fixed

Revision ID: 53cc788bbdf9
Revises: 94958c4e7a90
Create Date: 2026-05-04 19:13:10.212424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53cc788bbdf9'
down_revision: Union[str, Sequence[str], None] = '94958c4e7a90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mp_plan_id', sa.String(), nullable=False),
    sa.Column('name', sa.Enum('basic', 'premium', 'enterprise', name='plansenum'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_amount'), 'plans', ['amount'], unique=False)
    op.create_index(op.f('ix_plans_currency'), 'plans', ['currency'], unique=False)
    op.create_index(op.f('ix_plans_frequency'), 'plans', ['frequency'], unique=False)
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_plans_mp_plan_id'), 'plans', ['mp_plan_id'], unique=False)
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=False)
    op.create_foreign_key(None, 'subscription', 'plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_index(op.f('ix_plans_mp_plan_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_frequency'), table_name='plans')
    op.drop_index(op.f('ix_plans_currency'), table_name='plans')
    op.drop_index(op.f('ix_plans_amount'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
