"""cronograma db

Revision ID: 6228ad674f6b
Revises: fb889c75ef78
Create Date: 2026-06-08 11:16:35.570351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6228ad674f6b'
down_revision: Union[str, Sequence[str], None] = 'fb889c75ef78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_tasks', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'schedule_tasks', 'schedule_categories', ['category_id'], ['id'])
    op.drop_column('schedule_tasks', 'stage')
    op.add_column('weekly_schedules', sa.Column('is_current', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_schedules', 'is_current')
    op.add_column('schedule_tasks', sa.Column('stage', postgresql.ENUM('protection', 'preparation', 'assembly', 'validation', 'review', name='taskstatusenum'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'schedule_tasks', type_='foreignkey')
    op.drop_column('schedule_tasks', 'category_id')
    # ### end Alembic commands ###
