"""created company_join_requests in users db

Revision ID: 68d321a9fd73
Revises: af0fb2b3a708
Create Date: 2026-03-12 22:50:22.243811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68d321a9fd73'
down_revision: Union[str, Sequence[str], None] = 'af0fb2b3a708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.drop_index(op.f('ix_company_join_request_id'), table_name='company_join_request')
    op.drop_index(op.f('ix_company_join_request_status'), table_name='company_join_request')
    op.drop_table('company_join_request')
    op.create_index(
        op.f('ix_company_join_requests_company_id'),
        'company_join_requests',
        ['company_id'],
        unique=False
    )

    op.create_index(
        op.f('ix_company_join_requests_user_id'),
        'company_join_requests',
        ['user_id'],
        unique=False
    )
    op.add_column(
        'users',
        sa.Column('role', sa.String(), nullable=False, server_default='pending')
    )

    op.create_index(
        op.f('ix_users_role'),
        'users',
        ['role'],
        unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_column('users', 'role')
    op.drop_index(op.f('ix_company_join_requests_user_id'), table_name='company_join_requests')
    op.drop_index(op.f('ix_company_join_requests_company_id'), table_name='company_join_requests')
    op.create_table('company_join_request',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('company_join_request_company_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('company_join_request_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('company_join_request_pkey'))
    )
    op.create_index(op.f('ix_company_join_request_status'), 'company_join_request', ['status'], unique=False)
    op.create_index(op.f('ix_company_join_request_id'), 'company_join_request', ['id'], unique=False)
    # ### end Alembic commands ###
