"""add message in company_join_request

Revision ID: 6955aeb27ca3
Revises: 68d321a9fd73
Create Date: 2026-03-14 13:47:36.606447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6955aeb27ca3'
down_revision: Union[str, Sequence[str], None] = '68d321a9fd73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_join_requests', sa.Column('message', sa.String(), nullable=False))
    op.create_index(op.f('ix_company_join_requests_message'), 'company_join_requests', ['message'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_join_requests_message'), table_name='company_join_requests')
    op.drop_column('company_join_requests', 'message')
    # ### end Alembic commands ###
