"""add company id in all databases

Revision ID: 6a516ec53988
Revises: 78b982b3ce46
Create Date: 2026-03-08 18:10:23.807793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a516ec53988'
down_revision: Union[str, Sequence[str], None] = '78b982b3ce46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_logs_id'), table_name='inventory_logs')
    op.drop_table('inventory_logs')
    op.add_column('contacts', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('contacts', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contacts', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'contacts', 'companies', ['company_id'], ['id'])
    op.add_column('production', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('production', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'production', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'production', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'production', type_='foreignkey')
    op.drop_constraint(None, 'production', type_='foreignkey')
    op.drop_column('production', 'company_id')
    op.drop_column('production', 'owner_id')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'company_id')
    op.drop_column('contacts', 'owner_id')
    op.create_table('inventory_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('inventory_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quantity_changed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], name=op.f('inventory_logs_inventory_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('inventory_logs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('inventory_logs_pkey'))
    )
    op.create_index(op.f('ix_inventory_logs_id'), 'inventory_logs', ['id'], unique=False)
    # ### end Alembic commands ###
