"""moduls db in payments

Revision ID: 71248d0c5b5d
Revises: 016f6d5b21ca
Create Date: 2026-06-16 17:00:30.260225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71248d0c5b5d'
down_revision: Union[str, Sequence[str], None] = '016f6d5b21ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moduls', sa.Column('slug', sa.String(), nullable=False))
    op.create_index(op.f('ix_moduls_slug'), 'moduls', ['slug'], unique=False)
    op.add_column('moduls_companies', sa.Column('modul_id', sa.Integer(), nullable=False))
    op.add_column('moduls_companies', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'moduls_companies', 'moduls', ['modul_id'], ['id'])
    op.create_foreign_key(None, 'moduls_companies', 'companies', ['company_id'], ['id'])
    op.add_column('subscription', sa.Column('frequency', sa.String(), nullable=True))
    op.alter_column('subscription', 'amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True)
    op.drop_index(op.f('ix_subscription_plan_id'), table_name='subscription')
    op.create_index(op.f('ix_subscription_amount'), 'subscription', ['amount'], unique=False)
    op.create_index(op.f('ix_subscription_frequency'), 'subscription', ['frequency'], unique=False)
    op.drop_constraint(op.f('subscription_plan_id_fkey'), 'subscription', type_='foreignkey')
    op.drop_column('subscription', 'plan_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('subscription_plan_id_fkey'), 'subscription', 'plans', ['plan_id'], ['id'])
    op.drop_index(op.f('ix_subscription_frequency'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_amount'), table_name='subscription')
    op.create_index(op.f('ix_subscription_plan_id'), 'subscription', ['plan_id'], unique=False)
    op.alter_column('subscription', 'amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)
    op.drop_column('subscription', 'frequency')
    op.drop_constraint(None, 'moduls_companies', type_='foreignkey')
    op.drop_constraint(None, 'moduls_companies', type_='foreignkey')
    op.drop_column('moduls_companies', 'company_id')
    op.drop_column('moduls_companies', 'modul_id')
    op.drop_index(op.f('ix_moduls_slug'), table_name='moduls')
    op.drop_column('moduls', 'slug')
    # ### end Alembic commands ###
