"""add projects db

Revision ID: 84af9d997a6f
Revises: 
Create Date: 2026-04-15 23:23:46.139402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = '84af9d997a6f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.create_table(
        'projects',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('carpenter_id', sa.Integer(), nullable=False),

        sa.Column('client_id', sa.Integer(), nullable=False),
        sa.Column('client_name', sa.String(), nullable=False),

        sa.Column('delivery', sa.Date(), nullable=False),

        sa.Column(
            'status',
            sa.Enum(
                'planning', 'cutting', 'pre_assembly', 'lamination',
                'truck_loading', 'installation', 'completed', 'cancelled',
                name='statusenum',
                create_type=False
            ),
            nullable=False
        ),

        sa.Column('photo_path', sa.String(), nullable=False),
        sa.Column('pdf_path', sa.String(), nullable=False),
        sa.Column('pdf_url', sa.String(), nullable=False),

        sa.Column('created_at', sa.Date(), nullable=False),

        sa.Column('description', sa.String(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),

        sa.Column('active', sa.Boolean(), nullable=False),
        sa.Column('address', sa.String(), nullable=False),

        sa.ForeignKeyConstraint(['carpenter_id'], ['users.id']),
        sa.ForeignKeyConstraint(['client_id'], ['users.id']),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id']),

        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_projects_active'), 'projects', ['active'])
    op.create_index(op.f('ix_projects_address'), 'projects', ['address'])
    op.create_index(op.f('ix_projects_carpenter_id'), 'projects', ['carpenter_id'])
    op.create_index(op.f('ix_projects_client_id'), 'projects', ['client_id'])
    op.create_index(op.f('ix_projects_client_name'), 'projects', ['client_name'])
    op.create_index(op.f('ix_projects_company_id'), 'projects', ['company_id'])
    op.create_index(op.f('ix_projects_delivery'), 'projects', ['delivery'])
    op.create_index(op.f('ix_projects_description'), 'projects', ['description'])
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'])
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'])
    op.create_index(op.f('ix_projects_pdf_path'), 'projects', ['pdf_path'])
    op.create_index(op.f('ix_projects_pdf_url'), 'projects', ['pdf_url'])
    op.create_index(op.f('ix_projects_photo_path'), 'projects', ['photo_path'])
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'])

    op.alter_column(
        'payments',
        'status',
        existing_type=sa.VARCHAR(),
        type_=sa.Enum(
            'pending', 'cancelled', 'paid', 'overdue',
            name='debtstatusenum',
            create_type=False
        ),
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receivables_receiver_id'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_payer_name'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_payer_id'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_id'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_due_date'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_description'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_company_id'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_amount'), table_name='receivables')
    op.drop_table('receivables')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_due_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_company_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_amount'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_transactions_reference_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_description'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_company_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_amount'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_sells_profit'), table_name='sells')
    op.drop_index(op.f('ix_sells_installments'), table_name='sells')
    op.drop_index(op.f('ix_sells_income'), table_name='sells')
    op.drop_index(op.f('ix_sells_id'), table_name='sells')
    op.drop_index(op.f('ix_sells_expenses'), table_name='sells')
    op.drop_index(op.f('ix_sells_company_id'), table_name='sells')
    op.drop_index(op.f('ix_sells_client_name'), table_name='sells')
    op.drop_index(op.f('ix_sells_client_id'), table_name='sells')
    op.drop_table('sells')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_photo_path'), table_name='projects')
    op.drop_index(op.f('ix_projects_pdf_url'), table_name='projects')
    op.drop_index(op.f('ix_projects_pdf_path'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_description'), table_name='projects')
    op.drop_index(op.f('ix_projects_delivery'), table_name='projects')
    op.drop_index(op.f('ix_projects_company_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_client_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_client_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_carpenter_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_address'), table_name='projects')
    op.drop_index(op.f('ix_projects_active'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_production_id'), table_name='production')
    op.drop_index(op.f('ix_production_client_name'), table_name='production')
    op.drop_table('production')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_company_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_inventory_item_name'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_debts_id'), table_name='debts')
    op.drop_index(op.f('ix_debts_creditor'), table_name='debts')
    op.drop_index(op.f('ix_debts_company_id'), table_name='debts')
    op.drop_index(op.f('ix_debts_amount'), table_name='debts')
    op.drop_table('debts')
    op.drop_index(op.f('ix_contacts_phone'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_company_join_requests_user_id'), table_name='company_join_requests')
    op.drop_index(op.f('ix_company_join_requests_status'), table_name='company_join_requests')
    op.drop_index(op.f('ix_company_join_requests_message'), table_name='company_join_requests')
    op.drop_index(op.f('ix_company_join_requests_id'), table_name='company_join_requests')
    op.drop_index(op.f('ix_company_join_requests_company_id'), table_name='company_join_requests')
    op.drop_table('company_join_requests')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_companies_tax_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_legal_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_email'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
