"""search link

Revision ID: 903c04f80e66
Revises: 6228ad674f6b
Create Date: 2026-06-08 15:20:54.524016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '903c04f80e66'
down_revision: Union[str, Sequence[str], None] = '6228ad674f6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_schedule_categories_name'), 'schedule_categories', ['name'], unique=False)
    op.add_column('weekly_schedules', sa.Column('shared_link', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'weekly_schedules', ['shared_link'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weekly_schedules', type_='unique')
    op.drop_column('weekly_schedules', 'shared_link')
    op.drop_index(op.f('ix_schedule_categories_name'), table_name='schedule_categories')
    # ### end Alembic commands ###
