"""fixed: receivables.status

Revision ID: a0a3fc47fe9d
Revises: d439f23641f9
Create Date: 2026-04-03 21:26:09.554750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a3fc47fe9d'
down_revision: Union[str, Sequence[str], None] = 'd439f23641f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debts', sa.Column('notification', sa.Boolean(), nullable=False))
    op.add_column('receivables', sa.Column('status', sa.Enum('pending', 'paid', 'cancelled', 'overdue', name='receivablesstatusenum'), nullable=True))
    op.add_column('receivables', sa.Column('notification', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receivables', 'notification')
    op.drop_column('receivables', 'status')
    op.drop_column('debts', 'notification')
    # ### end Alembic commands ###
