"""add date_sell in sells db and kdi done

Revision ID: a526fac10a05
Revises: 4a0a03f7496c
Create Date: 2026-04-01 20:43:30.224186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a526fac10a05'
down_revision: Union[str, Sequence[str], None] = '4a0a03f7496c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sells', sa.Column('date_sell', sa.Date(), nullable=False))
    op.alter_column('sells', 'installments',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sells', 'delivery',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)
    op.create_index(op.f('ix_sells_profit'), 'sells', ['profit'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sells_profit'), table_name='sells')
    op.alter_column('sells', 'delivery',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('sells', 'installments',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('sells', 'date_sell')
    # ### end Alembic commands ###
