"""numeor cuota in receivable

Revision ID: a6ffc1f28508
Revises: 462c4b990765
Create Date: 2026-05-26 20:40:23.290447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6ffc1f28508'
down_revision: Union[str, Sequence[str], None] = '462c4b990765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receivables', sa.Column('numero_cuota', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_receivables_numero_cuota'), 'receivables', ['numero_cuota'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receivables_numero_cuota'), table_name='receivables')
    op.drop_column('receivables', 'numero_cuota')
    # ### end Alembic commands ###
