"""numeor cuota in receivable2

Revision ID: a9b71d2bdc0d
Revises: a6ffc1f28508
Create Date: 2026-05-26 20:55:42.858424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9b71d2bdc0d'
down_revision: Union[str, Sequence[str], None] = 'a6ffc1f28508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receivables', sa.Column('numero_cuota_format', sa.String(), nullable=True))
    op.create_index(op.f('ix_receivables_numero_cuota_format'), 'receivables', ['numero_cuota_format'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receivables_numero_cuota_format'), table_name='receivables')
    op.drop_column('receivables', 'numero_cuota_format')
    # ### end Alembic commands ###
