"""fix: projects

Revision ID: b94b78eacd74
Revises: 84af9d997a6f
Create Date: 2026-04-15 23:35:50.913570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b94b78eacd74'
down_revision: Union[str, Sequence[str], None] = '84af9d997a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_legal_name'), 'companies', ['legal_name'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_foreign_key(None, 'companies', 'users', ['owner_id'], ['id'])
    op.alter_column('company_join_requests', 'message',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_company_join_requests_company_id'), 'company_join_requests', ['company_id'], unique=False)
    op.create_index(op.f('ix_company_join_requests_id'), 'company_join_requests', ['id'], unique=False)
    op.create_index(op.f('ix_company_join_requests_message'), 'company_join_requests', ['message'], unique=False)
    op.create_index(op.f('ix_company_join_requests_status'), 'company_join_requests', ['status'], unique=False)
    op.create_index(op.f('ix_company_join_requests_user_id'), 'company_join_requests', ['user_id'], unique=False)
    op.create_foreign_key(None, 'company_join_requests', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'company_join_requests', 'companies', ['company_id'], ['id'])
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=True)
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_index(op.f('ix_contacts_name'), 'contacts', ['name'], unique=False)
    op.create_index(op.f('ix_contacts_phone'), 'contacts', ['phone'], unique=True)
    op.create_foreign_key(None, 'contacts', 'companies', ['company_id'], ['id'])
    op.alter_column('debts', 'status',
               existing_type=postgresql.ENUM('pending', 'cancelled', 'paid', 'overdue', name='debtstatusenum'),
               nullable=False)
    op.create_index(op.f('ix_debts_amount'), 'debts', ['amount'], unique=False)
    op.create_index(op.f('ix_debts_company_id'), 'debts', ['company_id'], unique=False)
    op.create_index(op.f('ix_debts_creditor'), 'debts', ['creditor'], unique=False)
    op.create_index(op.f('ix_debts_id'), 'debts', ['id'], unique=False)
    op.create_foreign_key(None, 'debts', 'companies', ['company_id'], ['id'])
    op.create_index(op.f('ix_inventory_id'), 'inventory', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_item_name'), 'inventory', ['item_name'], unique=False)
    op.create_foreign_key(None, 'inventory', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'inventory', 'users', ['owner_id'], ['id'])
    op.alter_column('notifications', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_notifications_company_id'), 'notifications', ['company_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'companies', ['company_id'], ['id'])
    op.alter_column('payments', 'paid',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('pending', 'cancelled', 'paid', 'overdue', name='debtstatusenum'),
               nullable=False)
    op.create_index(op.f('ix_payments_amount'), 'payments', ['amount'], unique=False)
    op.create_index(op.f('ix_payments_company_id'), 'payments', ['company_id'], unique=False)
    op.create_index(op.f('ix_payments_due_date'), 'payments', ['due_date'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_foreign_key(None, 'payments', 'debts', ['debt_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'payments', 'companies', ['company_id'], ['id'])
    op.create_index(op.f('ix_production_client_name'), 'production', ['client_name'], unique=False)
    op.create_index(op.f('ix_production_id'), 'production', ['id'], unique=False)
    op.create_foreign_key(None, 'production', 'companies', ['company_id'], ['id'])
    op.alter_column('projects', 'carpenter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('projects', 'delivery',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('projects', 'status',
               existing_type=postgresql.ENUM('planning', 'cutting', 'pre_assembly', 'lamination', 'truck_loading', 'installation', 'completed', 'cancelled', name='statusenum'),
               nullable=False)
    op.alter_column('projects', 'created_at',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('projects', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('projects', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_projects_active'), 'projects', ['active'], unique=False)
    op.create_index(op.f('ix_projects_address'), 'projects', ['address'], unique=False)
    op.create_index(op.f('ix_projects_carpenter_id'), 'projects', ['carpenter_id'], unique=False)
    op.create_index(op.f('ix_projects_client_id'), 'projects', ['client_id'], unique=False)
    op.create_index(op.f('ix_projects_client_name'), 'projects', ['client_name'], unique=False)
    op.create_index(op.f('ix_projects_company_id'), 'projects', ['company_id'], unique=False)
    op.create_index(op.f('ix_projects_delivery'), 'projects', ['delivery'], unique=False)
    op.create_index(op.f('ix_projects_description'), 'projects', ['description'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_pdf_path'), 'projects', ['pdf_path'], unique=False)
    op.create_index(op.f('ix_projects_pdf_url'), 'projects', ['pdf_url'], unique=False)
    op.create_index(op.f('ix_projects_photo_path'), 'projects', ['photo_path'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_foreign_key(None, 'projects', 'users', ['carpenter_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'users', ['client_id'], ['id'])
    op.create_index(op.f('ix_receivables_amount'), 'receivables', ['amount'], unique=False)
    op.create_index(op.f('ix_receivables_company_id'), 'receivables', ['company_id'], unique=False)
    op.create_index(op.f('ix_receivables_description'), 'receivables', ['description'], unique=False)
    op.create_index(op.f('ix_receivables_due_date'), 'receivables', ['due_date'], unique=False)
    op.create_index(op.f('ix_receivables_id'), 'receivables', ['id'], unique=False)
    op.create_index(op.f('ix_receivables_payer_id'), 'receivables', ['payer_id'], unique=False)
    op.create_index(op.f('ix_receivables_payer_name'), 'receivables', ['payer_name'], unique=False)
    op.create_index(op.f('ix_receivables_receiver_id'), 'receivables', ['receiver_id'], unique=False)
    op.create_foreign_key(None, 'receivables', 'users', ['receiver_id'], ['id'])
    op.create_foreign_key(None, 'receivables', 'contacts', ['payer_id'], ['id'])
    op.create_foreign_key(None, 'receivables', 'companies', ['company_id'], ['id'])
    op.alter_column('sells', 'status',
               existing_type=postgresql.ENUM('planning', 'cutting', 'pre_assembly', 'lamination', 'truck_loading', 'installation', 'completed', 'cancelled', name='statusenum'),
               nullable=False)
    op.create_index(op.f('ix_sells_client_id'), 'sells', ['client_id'], unique=False)
    op.create_index(op.f('ix_sells_client_name'), 'sells', ['client_name'], unique=False)
    op.create_index(op.f('ix_sells_company_id'), 'sells', ['company_id'], unique=False)
    op.create_index(op.f('ix_sells_expenses'), 'sells', ['expenses'], unique=False)
    op.create_index(op.f('ix_sells_id'), 'sells', ['id'], unique=False)
    op.create_index(op.f('ix_sells_income'), 'sells', ['income'], unique=False)
    op.create_index(op.f('ix_sells_installments'), 'sells', ['installments'], unique=False)
    op.create_index(op.f('ix_sells_profit'), 'sells', ['profit'], unique=False)
    op.create_foreign_key(None, 'sells', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'sells', 'users', ['client_id'], ['id'])
    op.create_foreign_key(None, 'sells', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'sells', 'users', ['carpenter_id'], ['id'])
    op.create_index(op.f('ix_transactions_amount'), 'transactions', ['amount'], unique=False)
    op.create_index(op.f('ix_transactions_company_id'), 'transactions', ['company_id'], unique=False)
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_description'), 'transactions', ['description'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_reference_id'), 'transactions', ['reference_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'companies', ['company_id'], ['id'])
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_reference_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_description'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_company_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_amount'), table_name='transactions')
    op.drop_constraint(None, 'sells', type_='foreignkey')
    op.drop_constraint(None, 'sells', type_='foreignkey')
    op.drop_constraint(None, 'sells', type_='foreignkey')
    op.drop_constraint(None, 'sells', type_='foreignkey')
    op.drop_index(op.f('ix_sells_profit'), table_name='sells')
    op.drop_index(op.f('ix_sells_installments'), table_name='sells')
    op.drop_index(op.f('ix_sells_income'), table_name='sells')
    op.drop_index(op.f('ix_sells_id'), table_name='sells')
    op.drop_index(op.f('ix_sells_expenses'), table_name='sells')
    op.drop_index(op.f('ix_sells_company_id'), table_name='sells')
    op.drop_index(op.f('ix_sells_client_name'), table_name='sells')
    op.drop_index(op.f('ix_sells_client_id'), table_name='sells')
    op.alter_column('sells', 'status',
               existing_type=postgresql.ENUM('planning', 'cutting', 'pre_assembly', 'lamination', 'truck_loading', 'installation', 'completed', 'cancelled', name='statusenum'),
               nullable=True)
    op.drop_constraint(None, 'receivables', type_='foreignkey')
    op.drop_constraint(None, 'receivables', type_='foreignkey')
    op.drop_constraint(None, 'receivables', type_='foreignkey')
    op.drop_index(op.f('ix_receivables_receiver_id'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_payer_name'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_payer_id'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_id'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_due_date'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_description'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_company_id'), table_name='receivables')
    op.drop_index(op.f('ix_receivables_amount'), table_name='receivables')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_photo_path'), table_name='projects')
    op.drop_index(op.f('ix_projects_pdf_url'), table_name='projects')
    op.drop_index(op.f('ix_projects_pdf_path'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_description'), table_name='projects')
    op.drop_index(op.f('ix_projects_delivery'), table_name='projects')
    op.drop_index(op.f('ix_projects_company_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_client_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_client_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_carpenter_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_address'), table_name='projects')
    op.drop_index(op.f('ix_projects_active'), table_name='projects')
    op.alter_column('projects', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('projects', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('projects', 'created_at',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('projects', 'status',
               existing_type=postgresql.ENUM('planning', 'cutting', 'pre_assembly', 'lamination', 'truck_loading', 'installation', 'completed', 'cancelled', name='statusenum'),
               nullable=True)
    op.alter_column('projects', 'delivery',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('projects', 'carpenter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'production', type_='foreignkey')
    op.drop_index(op.f('ix_production_id'), table_name='production')
    op.drop_index(op.f('ix_production_client_name'), table_name='production')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_due_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_company_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_amount'), table_name='payments')
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('pending', 'cancelled', 'paid', 'overdue', name='debtstatusenum'),
               nullable=True)
    op.alter_column('payments', 'paid',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_company_id'), table_name='notifications')
    op.alter_column('notifications', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_constraint(None, 'inventory', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_item_name'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_id'), table_name='inventory')
    op.drop_constraint(None, 'debts', type_='foreignkey')
    op.drop_index(op.f('ix_debts_id'), table_name='debts')
    op.drop_index(op.f('ix_debts_creditor'), table_name='debts')
    op.drop_index(op.f('ix_debts_company_id'), table_name='debts')
    op.drop_index(op.f('ix_debts_amount'), table_name='debts')
    op.alter_column('debts', 'status',
               existing_type=postgresql.ENUM('pending', 'cancelled', 'paid', 'overdue', name='debtstatusenum'),
               nullable=True)
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.drop_index(op.f('ix_contacts_phone'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_constraint(None, 'company_join_requests', type_='foreignkey')
    op.drop_constraint(None, 'company_join_requests', type_='foreignkey')
    op.drop_index(op.f('ix_company_join_requests_user_id'), table_name='company_join_requests')
    op.drop_index(op.f('ix_company_join_requests_status'), table_name='company_join_requests')
    op.drop_index(op.f('ix_company_join_requests_message'), table_name='company_join_requests')
    op.drop_index(op.f('ix_company_join_requests_id'), table_name='company_join_requests')
    op.drop_index(op.f('ix_company_join_requests_company_id'), table_name='company_join_requests')
    op.alter_column('company_join_requests', 'message',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'companies', type_='foreignkey')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_legal_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    # ### end Alembic commands ###
