"""projects db chore

Revision ID: c199d908b16e
Revises: e7a6a9ab896d
Create Date: 2026-05-22 16:37:13.874508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c199d908b16e'
down_revision: Union[str, Sequence[str], None] = 'e7a6a9ab896d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('author_name', sa.String(), nullable=False))
    op.add_column('comments', sa.Column('session_token', sa.String(), nullable=True))
    op.alter_column('comments', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_comments_author_name'), 'comments', ['author_name'], unique=False)
    op.create_index(op.f('ix_comments_session_token'), 'comments', ['session_token'], unique=True)
    op.create_index(op.f('ix_comments_text'), 'comments', ['text'], unique=False)
    op.add_column('shared_projects', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_shared_projects_company_id'), 'shared_projects', ['company_id'], unique=False)
    op.create_foreign_key(None, 'shared_projects', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shared_projects', type_='foreignkey')
    op.drop_index(op.f('ix_shared_projects_company_id'), table_name='shared_projects')
    op.drop_column('shared_projects', 'company_id')
    op.drop_index(op.f('ix_comments_text'), table_name='comments')
    op.drop_index(op.f('ix_comments_session_token'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_name'), table_name='comments')
    op.alter_column('comments', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('comments', 'session_token')
    op.drop_column('comments', 'author_name')
    # ### end Alembic commands ###
