"""el company name en singup no es obligatorio

Revision ID: d1aca8bc09e4
Revises: b94b78eacd74
Create Date: 2026-04-16 22:27:07.964640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1aca8bc09e4'
down_revision: Union[str, Sequence[str], None] = 'b94b78eacd74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_client_id'), table_name='projects')
    op.drop_constraint(op.f('projects_client_id_fkey'), 'projects', type_='foreignkey')
    op.drop_column('projects', 'client_id')
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.add_column('projects', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('projects_client_id_fkey'), 'projects', 'users', ['client_id'], ['id'])
    op.create_index(op.f('ix_projects_client_id'), 'projects', ['client_id'], unique=False)
    # ### end Alembic commands ###
