"""installments and date_sells nullable=False

Revision ID: d439f23641f9
Revises: dbdc28931830
Create Date: 2026-04-03 01:21:26.911713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd439f23641f9'
down_revision: Union[str, Sequence[str], None] = 'dbdc28931830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sells', 'installments',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sells', 'date_sell',
               existing_type=sa.DATE(),
               nullable=True)
    op.execute("UPDATE sells SET installments = 1")
    op.execute("UPDATE sells SET date_sell = '2000-01-01'")
    op.alter_column('sells', 'installments',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sells', 'date_sell',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sells', 'date_sell',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('sells', 'installments',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
