"""financery db, dont remenber what i did lmao

Revision ID: dbdc28931830
Revises: a526fac10a05
Create Date: 2026-04-03 01:19:26.525978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbdc28931830'
down_revision: Union[str, Sequence[str], None] = 'a526fac10a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('installment_number', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('total_installments', sa.Integer(), nullable=False))
    op.alter_column('sells', 'installments',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sells', 'date_sell',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sells', 'date_sell',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('sells', 'installments',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('payments', 'total_installments')
    op.drop_column('payments', 'installment_number')
    # ### end Alembic commands ###
