"""delete owner in contacts and production db

Revision ID: e0191ce90b3d
Revises: 1ecb9b7056b7
Create Date: 2026-03-08 18:27:29.522960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0191ce90b3d'
down_revision: Union[str, Sequence[str], None] = '1ecb9b7056b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('contacts_owner_id_fkey'), 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'owner_id')
    op.drop_constraint(op.f('production_owner_id_fkey'), 'production', type_='foreignkey')
    op.drop_column('production', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('production', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('production_owner_id_fkey'), 'production', 'users', ['owner_id'], ['id'])
    op.add_column('contacts', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('contacts_owner_id_fkey'), 'contacts', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
