"""create cronograma db

Revision ID: e34bf63c2770
Revises: 31bae4b28f1a
Create Date: 2026-06-05 16:15:17.010648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e34bf63c2770'
down_revision: Union[str, Sequence[str], None] = '31bae4b28f1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    subscription_status_enum = sa.Enum(
        'active',
        'canceled',
        'overdue',
        'pending',
        'expired',
        name='subscriptionstatusenum'
    )

    subscription_status_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column(
        'subscription',
        'status',
        existing_type=sa.VARCHAR(),
        type_=subscription_status_enum,
        existing_nullable=False,
        postgresql_using="""
            CASE status
                WHEN 'Ativa' THEN 'active'
                WHEN 'Cancelada' THEN 'canceled'
                WHEN 'Vencida' THEN 'overdue'
                WHEN 'Pendente' THEN 'pending'
                WHEN 'Expirada' THEN 'expired'
            END::subscriptionstatusenum
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subscription', 'status',
               existing_type=sa.Enum('active', 'canceled', 'overdue', 'pending', 'expired', name='subscriptionstatusenum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
