"""plans external_id

Revision ID: e6af2f04f06e
Revises: f16a00a1be63
Create Date: 2026-06-02 08:05:29.619289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6af2f04f06e'
down_revision: Union[str, Sequence[str], None] = 'f16a00a1be63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('external_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_plans_external_id'), 'plans', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plans_external_id'), table_name='plans')
    op.drop_column('plans', 'external_id')
    # ### end Alembic commands ###
