"""search token

Revision ID: e7cacb788f2a
Revises: 903c04f80e66
Create Date: 2026-06-09 10:52:29.216252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7cacb788f2a'
down_revision: Union[str, Sequence[str], None] = '903c04f80e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_schedules', sa.Column('shared_token', sa.String(), nullable=True))
    op.drop_constraint(op.f('weekly_schedules_shared_link_key'), 'weekly_schedules', type_='unique')
    op.create_unique_constraint(None, 'weekly_schedules', ['shared_token'])
    op.drop_column('weekly_schedules', 'shared_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_schedules', sa.Column('shared_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'weekly_schedules', type_='unique')
    op.create_unique_constraint(op.f('weekly_schedules_shared_link_key'), 'weekly_schedules', ['shared_link'])
    op.drop_column('weekly_schedules', 'shared_token')
    # ### end Alembic commands ###
