"""payment refact

Revision ID: f16a00a1be63
Revises: a9b71d2bdc0d
Create Date: 2026-06-01 12:49:04.580496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f16a00a1be63'
down_revision: Union[str, Sequence[str], None] = 'a9b71d2bdc0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    subscription_status_enum = postgresql.ENUM(
        'active',
        'canceled',
        'overdue',
        'pending',
        'expired',
        name='subscriptionstatusenum'
    )

    subscription_status_enum.create(op.get_bind(), checkfirst=True)

    op.drop_index(op.f('ix_plans_mp_plan_id'), table_name='plans')
    op.drop_column('plans', 'mp_plan_id')

    op.add_column(
        'subscription',
        sa.Column('current_period_start', sa.Date(), nullable=False)
    )

    op.add_column(
        'subscription',
        sa.Column('cancel_at_period_end', sa.Date(), nullable=True)
    )

    op.add_column(
        'subscription',
        sa.Column('current_period_end', sa.Date(), nullable=False)
    )

    op.add_column(
        'subscription',
        sa.Column('payment_provider_id', sa.String(), nullable=True)
    )

    op.add_column(
        'subscription',
        sa.Column('is_active', sa.Boolean(), nullable=True)
    )

    op.alter_column(
        'subscription',
        'status',
        existing_type=sa.VARCHAR(),
        type_=sa.Enum(
            'active',
            'canceled',
            'overdue',
            'pending',
            'expired',
            name='subscriptionstatusenum'
        ),
        postgresql_using='status::subscriptionstatusenum',
        existing_nullable=False
    )

    op.create_index(
        op.f('ix_subscription_cancel_at_period_end'),
        'subscription',
        ['cancel_at_period_end'],
        unique=False
    )

    op.drop_column('subscription', 'active')
    op.drop_column('subscription', 'mp_subscription_id')
    op.drop_column('subscription', 'end_date')
    op.drop_column('subscription', 'start_date')

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('subscription', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('subscription', sa.Column('mp_subscription_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('subscription', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_subscription_cancel_at_period_end'), table_name='subscription')
    op.alter_column('subscription', 'status',
               existing_type=sa.Enum('active', 'canceled', 'overdue', 'pending', 'expired', name='subscriptionstatusenum'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('subscription', 'is_active')
    op.drop_column('subscription', 'payment_provider_id')
    op.drop_column('subscription', 'current_period_end')
    op.drop_column('subscription', 'cancel_at_period_end')
    op.drop_column('subscription', 'current_period_start')
    op.add_column('plans', sa.Column('mp_plan_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_plans_mp_plan_id'), 'plans', ['mp_plan_id'], unique=False)
    # ### end Alembic commands ###
