"""moduls db in payments 2

Revision ID: f6494791cb0d
Revises: 71248d0c5b5d
Create Date: 2026-06-17 20:55:27.792886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6494791cb0d'
down_revision: Union[str, Sequence[str], None] = '71248d0c5b5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('plan_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_subscription_plan_id'), 'subscription', ['plan_id'], unique=False)
    op.create_foreign_key(None, 'subscription', 'plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription', type_='foreignkey')
    op.drop_index(op.f('ix_subscription_plan_id'), table_name='subscription')
    op.drop_column('subscription', 'plan_id')
    # ### end Alembic commands ###
