"""create cronograma db

Revision ID: fb889c75ef78
Revises: e34bf63c2770
Create Date: 2026-06-05 16:20:00.285546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb889c75ef78'
down_revision: Union[str, Sequence[str], None] = 'e34bf63c2770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table(
        'weekly_schedules',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('start', sa.Date(), nullable=False),
        sa.Column('end', sa.Date(), nullable=False),
        sa.Column('notes', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id']),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_weekly_schedules_company_id'), 'weekly_schedules', ['company_id'], unique=False)
    op.create_index(op.f('ix_weekly_schedules_end'), 'weekly_schedules', ['end'], unique=False)
    op.create_index(op.f('ix_weekly_schedules_id'), 'weekly_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_schedules_start'), 'weekly_schedules', ['start'], unique=False)
    op.create_index(op.f('ix_weekly_schedules_title'), 'weekly_schedules', ['title'], unique=False)

    op.create_table(
        'schedule_tasks',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('weekly_schedule_id', sa.Integer(), nullable=False),
        sa.Column('day_of_week', sa.String(), nullable=False),
        sa.Column('activity', sa.String(), nullable=False),
        sa.Column(
            'stage',
            sa.Enum(
                'protection',
                'preparation',
                'assembly',
                'validation',
                'review',
                name='taskstatusenum'
            ),
            nullable=False
        ),
        sa.Column('order_position', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['weekly_schedule_id'], ['weekly_schedules.id']),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_schedule_tasks_id'), 'schedule_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_schedule_tasks_weekly_schedule_id'), 'schedule_tasks', ['weekly_schedule_id'], unique=False)

    op.create_table(
        'weekly_milestones',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('weekly_schedule_id', sa.Integer(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('completed', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['weekly_schedule_id'], ['weekly_schedules.id']),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_index(op.f('ix_weekly_milestones_id'), 'weekly_milestones', ['id'], unique=False)
    op.create_index(op.f('ix_weekly_milestones_weekly_schedule_id'), 'weekly_milestones', ['weekly_schedule_id'], unique=False)

    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_milestones_weekly_schedule_id'), table_name='weekly_milestones')
    op.drop_index(op.f('ix_weekly_milestones_id'), table_name='weekly_milestones')
    op.drop_table('weekly_milestones')
    op.drop_index(op.f('ix_schedule_tasks_weekly_schedule_id'), table_name='schedule_tasks')
    op.drop_index(op.f('ix_schedule_tasks_id'), table_name='schedule_tasks')
    op.drop_table('schedule_tasks')
    op.drop_index(op.f('ix_weekly_schedules_title'), table_name='weekly_schedules')
    op.drop_index(op.f('ix_weekly_schedules_start'), table_name='weekly_schedules')
    op.drop_index(op.f('ix_weekly_schedules_id'), table_name='weekly_schedules')
    op.drop_index(op.f('ix_weekly_schedules_end'), table_name='weekly_schedules')
    op.drop_index(op.f('ix_weekly_schedules_company_id'), table_name='weekly_schedules')
    op.drop_table('weekly_schedules')
    # ### end Alembic commands ###
